export interface AShit {
  ShitID?: number; //adding the ? to make it optional, as it will be auto-generated by the backend
  Shitterid?: number;
  ToiletId?: number;
  Time?: Date;
  Rating?: number;
  Review?: string;
}