import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { Router } from '@angular/router';
import { Shitter } from '../model/shitter';
import { ShitterService } from '../services/shitter-service';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-signup',
  standalone: true,
  templateUrl: './page-sign-up.html',
  styleUrl: './page-sign-up.css',
  imports: [CommonModule, FormsModule],
})
export class PageSignUp implements OnInit {
  constructor(
    private shitterService: ShitterService,
    private cdr: ChangeDetectorRef,
    private router: Router,
  ) {}

  newShitter: Shitter = {
    Shitterid: 0,
    FirstName: '',
    LastName: '',
    Email: '',
    Password: '',
  };

  ngOnInit(): void {
    console.log('PageSignUp ngOnInit called');
  }

  errorMessage: string = '';

  signUp(): void {
    this.shitterService.createShitter(this.newShitter).subscribe(
      (response) => {
        console.log('Shitter created:', response);
        this.cdr.markForCheck();
        this.newShitter = {
          Shitterid: 0, //this is a placeholder. The actual ID will be auto-generated by the backend in numerical order from the most recent number. 
          FirstName: '',
          LastName: '',
          Email: '',
          Password: '',
        };
        this.router.navigate(['/shit-search']);
      },
      (error) => {
        if (error.status === 409) {
        this.errorMessage = 'An account with this email already exists.';
        } else {
          this.errorMessage = 'Something went wrong. Please try again.';
        }
      }
    );
  }
}