import { Component, OnInit, ChangeDetectorRef } from '@angular/core';
import { Router } from '@angular/router';
import { User } from '../model/user';
import { UserService } from '../services/user-service';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-signup',
  standalone: true,
  templateUrl: './page-sign-up.html',
  styleUrl: './page-sign-up.css',
  imports: [CommonModule, FormsModule],
})
export class PageSignUp implements OnInit {
  constructor(
    private userService: UserService,
    private cdr: ChangeDetectorRef,
    private router: Router,
  ) {}

  newUser: User = {
    Userid: 0,
    FirstName: '',
    LastName: '',
    Email: '',
    Password: '',
  };

  ngOnInit(): void {
    console.log('PageSignUp ngOnInit called');
  }

  errorMessage: string = '';

  signUp(): void {
    this.userService.createUser(this.newUser).subscribe(
      (response) => {
        console.log('User created:', response);
        this.cdr.markForCheck();
        this.newUser = {
          Userid: 0, //this is a placeholder. The actual ID will be auto-generated by the backend in numerical order from the most recent number.
          FirstName: '',
          LastName: '',
          Email: '',
          Password: '',
        };
        this.router.navigate(['/shit-search']);
      },
      (error) => {
        if (error.status === 409) {
          this.errorMessage = 'An account with this email already exists.';
        } else {
          this.errorMessage = 'Something went wrong. Please try again.';
        }
      },
    );
  }
}
